### ISSUE TITLE
HTTP Error 418

### ISSUE THREAD

**Issue by ModernAesthetics** [22nds/lynda-video-downloader#10]
Getting:
ERROR: Unable to download JSON metadata: HTTP Error 418:  (caused by <HTTPError 418: ''>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by bjarnemagnussen** [comment]
Are you sure you have added valid login credentials to `download.py`? This error message is one that I only get when using wrong/invalid login details.

**Comment by 22nds** [comment]
Tested the script on the latest youtube-dl version 2019.1.30.1 and it works. Make sure you have the right credentials.
