### ISSUE TITLE
download.py - accepting LinkedIn login

### ISSUE THREAD

**Issue by Capitalmind** [22nds/lynda-video-downloader#14]
At some point I switched my login from Lynda.com account to LinkedIn account and have tried all variations of username and password and am unable to login. Can this be fixed?

**Comment by 22nds** [comment]
Hi @Capitalmind,

Only Lynda.com login/password is accepted as Linkedin uses other technologies and they are not compatible. 

But maybe somebody else coded the solution for Linkedin - it's worth a check on github or google.

Best,
M.
