### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by baduker** [22nds/lynda-video-downloader#6]
I'm running a Mac OX Sierra with Python 3.6 and I'm getting this error:

`ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)'),))
Could not download the video in course: http://www.lynda.com/C-tutorials/C-Essential-Training/164457-2.html`

Any ideas how to get around it?

**Comment by 22nds** [comment]
Change `http` into `https` like below: 
https://www.lynda.com/C-tutorials/C-Essential-Training/164457-2.html

**Comment by baduker** [comment]
I did it but it didn't help yet stackoverflow came to the rescue.

Go to Applications/Python 3.6/Install Certificates.command and double click it. 

Now, the download.py works like a charm.

Thanks!

**Comment by 22nds** [comment]
Perfect! I am happy you found the solution.
