### ISSUE TITLE
Can you add organization login?

### ISSUE THREAD

**Issue by webeasyplay** [22nds/lynda-video-downloader#9]
Can you add organization login?

**Comment by 22nds** [comment]
I would like to add it in the future, but I don't have such account and I would need it for testing.

**Comment by webeasyplay** [comment]
I send the account for you!
Please check your gmail !

**Comment by jeremejazz** [comment]
Is this like library card? I'd like to help though I'll have to learn how to use youtube-dl for the moment. 
Would be a bit tricky though as library accounts have their own login page followed by a pin code. Youtube-dl seems to be a high-level library that only accepts video page URL and login account

**Comment by Adarsh777** [comment]
Please add organization log in. much needed.

**Comment by jeremejazz** [comment]
I think this proposal should go to youtube-dl since this program heavily relies on it. Try opening a ticket there to specify a specific login url, or adding cookies maybe

**Comment by MuhammadSaeedBatikh** [comment]
i just did the following

1- extracted cookies from lynda.com using cookies.txt extension and saved it into a file
2- declared a new variable:
                                           COOKIESFILE = 'path\to\my\cookies file' 

3- deleted USERNAME and PASSWORD from options and added 
'cookies': COOKIESFILE  to options instead

worked like a charm

**Comment by jeremejazz** [comment]
@MuhammadSaeedBatikh  you Sir are amazing! ... will try that

**Comment by lukasp1440** [comment]
Having trouble. The options passed to youtube-dl isn't accepting the cookies properly. It works fine when i use youtube-dl solo with the --cookies option. Is the spawning mechanism limited for its instantiation?

**Comment by jidslines** [comment]
@MuhammadSaeedBatikh Not quite although the general idea is the same.

This solution was achieved on Windows with Chrome.
My Full Solution:
1. Installed the cookies.txt plugin for chrome.
2. Sign into lynda.com in chrome.
3. Click ~ 'Download cookies for this tab' option in the cookies.txt extension, post lynda sign-in, on that same tab.
4. Copy this file to the same directory where the lynda downloader files are (e.g. where download.py is)
5. Edit download.py in the following ways: 
A. `COOKIESFILE = '../cookies.txt'` replaces the `USERNAME = 'your-username'` and 
`PASSWORD = 'your-password'` lines.
B. `'cookiefile': COOKIESFILE,` replaces the `'username': USERNAME,` and 'password': PASSWORD,` lines.
6. Proceed normally.

Please implement this as an option into the standard code base if possible (not retrieving the cookies, but the option & procedure to do so natively).

**Comment by eletricaraquete** [comment]
Did what @MuhammadSaeedBatikh said, but after downloaded the 5th video, its just stops... even if I try to download again, still stops on 5th... any ideas?

**Comment by eletricaraquete** [comment]
Tried again, with another course, and same behavior happened... even if I add more than one link in the txt file, only downloads 5 videos and stop.

**Comment by 22nds** [comment]
I will not be extending the functionality of the script to include organization login, but feel free to fork it and experiment with it.

**Comment by jeremejazz** [comment]
A feature like this is available on a similar project **[lynda-dl](https://github.com/r0oth3x49/lynda-dl)**
sample command: 
```bash
python lynda-dl.py -u library_card_num -p library_card_pin -o organization COURSE_URL  -d "/path/to/directory/" 
```
